title: Junika Tamang Portfolio
logo: Docs/Assets/IMG-20250226-WA0081.jpg
description: A personal student portfolio showcasing projects, skills, and contact info
baseurl: ""
Url: https://junika314.github.io/Junika314.guthub.io-/ 
theme: jekyll-theme-minimal
author:
  name:  Tamang Junika 
  email: tamangjunika338@gmail.com
