title: Junika Tamang Portfolio
description: A personal student portfolio showcasing projects, skills, and contact info
baseurl: ""
theme: jekyll-theme-minimal
author:
  name:  Tamang Junika 
  email: tamangjunika338@gmail.com
